import { Category } from "@material-ui/icons"

export const vegs = [
  { id: "unspecified", name: "未指定", category: "未指定" },  
  { id: "asparagus", name: "アスパラガス", category: "野菜" },  
  { id: "green_beans", name: "いんげんまめ", category: "野菜" },  
  { id: "edamame", name: "えだまめ", category: "野菜" },  
  { id: "okra", name: "オクラ", category: "野菜" },
  { id: "kaiware_daikon", name: "かいわれだいこん", category: "野菜" },
  { id: "turnip", name: "かぶ", category: "野菜" },
  { id: "pumpkin", name: "かぼちゃ", category: "野菜" },
  { id: "cauliflower", name: "カリフラワー", category: "野菜" },
  { id: "kanpyo", name: "かんぴょう", category: "野菜" },
  { id: "cabbage", name: "キャベツ", category: "野菜" },
  { id: "cucumber", name: "きゅうり", category: "野菜" },
  { id: "green_peas", name: "グリンピース", category: "野菜" },
  { id: "burdock", name: "ごぼう", category: "野菜" },
  { id: "komatsuna", name: "こまつな", category: "野菜" },
  { id: "sayaendo", name: "さやえんどう", category: "野菜" },
  { id: "sunny_lettuce", name: "サニーレタス", category: "野菜" },
  { id: "shiso", name: "しそ", category: "野菜" },
  { id: "crowndaisy", name: "春菊", category: "野菜" },
  { id: "potato", name: "じゃがいも", category: "野菜" },
  { id: "ginger", name: "しょうが", category: "野菜" },
  { id: "sweet_corn", name: "スイートコーン", category: "野菜" },
  { id: "celery", name: "セロリー", category: "野菜" },
  { id: "daikon_radish", name: "だいこん", category: "野菜" },   
  { id: "bambooshoot", name: "たけのこ", category: "野菜" },   
  { id: "onion", name: "玉ねぎ", category: "野菜" },   
  { id: "bok_choy", name: "チンゲン菜", category: "野菜" },  
  { id: "tomato", name: "トマト", category: "野菜" },  
  { id: "eggplant", name: "なす", category: "野菜" },  
  { id: "chinese_chive", name: "にら", category: "野菜" },  
  { id: "carrots", name: "にんじん", category: "野菜" },  
  { id: "garlic", name: "にんにく", category: "野菜" },  
  { id: "chinese_cabbage", name: "はくさい", category: "野菜" },  
  { id: "parsley", name: "パセリ", category: "野菜" },  
  { id: "green_pepper", name: "ピーマン", category: "野菜" },  
  { id: "broccoli", name: "ブロッコリー", category: "野菜" },  
  { id: "spinach", name: "ほうれんそう", category: "野菜" },  
  { id: "moroheiya", name: "モロヘイヤ", category: "野菜" },  
  { id: "bean_sprouts", name: "もやし", category: "野菜" },  
  { id: "mugwort", name: "よもぎ", category: "野菜" },  
  { id: "leaf_lettuce", name: "リーフレタス", category: "野菜" },  
  { id: "lettuce", name: "レタス", category: "野菜" },  
  { id: "lotus_root", name: "れんこん", category: "野菜" },  
    
]

export const meats = [
  { id: "unspecified", name: "未指定", category: "未指定" },
  { id: "wiener", name: "ウインナー", category: "肉" },   
  { id: "beaf", name: "牛肉", category: "肉" },   
  { id: "beef_liver", name: "牛レバー", category: "肉" },   
  { id: "sausage", name: "ソーセージ", category: "肉" },   
  { id:"chicken", name: "鶏肉", category: "肉" },  
  { id:"chicken_liver", name: "鶏レバー", category: "肉" },  
  { id: "horsemeat", name: "馬肉", category: "肉" },
  { id: "ham", name: "ハム", category: "肉" },
  { id: "pork", name: "豚肉", category: "肉" },
  { id: "pork_liver", name: "豚レバー", category: "肉" },
  { id: "bacon", name: "ベーコン", category: "肉" },
  { id: "grilled_pork", name: "焼き豚", category: "肉" },
    
]

export const fishes = [
  { id: "unspecified", name: "未指定", category: "未指定" },
  { id:"clams", name: "アサリ", category: "魚" },  
  { id:"horse_mackerel", name: "アジ", category: "魚" },  
  { id: "conger_eel", name: "アナゴ", category: "魚" },   
  { id: "squid", name: "イカ", category: "魚" },   
  { id: "sardine", name: "イワシ", category: "魚" },
  { id: "shrimp", name: "エビ", category: "魚" },
  { id: "swordfish", name: "カジキ", category: "魚" },
  { id: "skipjack", name: "カツオ", category: "魚" },
  { id: "katsuobushi", name: "かつお節", category: "魚" },
  { id: "kamaboko", name: "かまぼこ", category: "魚" },
  { id: "flatfish", name: "カレイ", category: "魚" },
  { id: "salmon", name: "サケ", category: "魚" },
  { id: "mackerel", name: "サバ", category: "魚" }, 
  { id: "spanish_mackerel", name: "サワラ", category: "魚" },
  { id: "shishamo", name: "シシャモ", category: "魚" },
  { id: "shirasu", name: "シラス", category: "魚" },
  { id: "sea_bass", name: "スズキ", category: "魚" },
  { id: "thailand", name: "タイ", category: "魚" },
  { id: "octopus", name: "タコ", category: "魚" },
  { id: "chikuwa", name: "ちくわ", category: "魚" },
  { id: "tuna_can", name: "ツナ缶", category: "魚" },
  { id: "flounder", name: "ヒラメ", category: "魚" },
  { id: "yellowtail", name: "ブリ", category: "魚" },
  { id: "tuna", name: "マグロ", category: "魚" },
  
]
      
export const cereals = [
  { id: "unspecified", name: "未指定", category: "未指定" },
  { id:"tomato", name: "白米", category: "穀類" },  
  { id: "onion", name: "おかゆ", category: "穀類" },   
  { id: "potato", name: "赤飯", category: "穀類" },
  { id: "potato", name: "食パン", category: "穀類" },
  { id: "potato", name: "フランスパン", category: "穀類" },
  { id: "potato", name: "ロールパン", category: "穀類" },
  { id: "potato", name: "クロワッサン", category: "穀類" },
  { id: "potato", name: "うどん", category: "穀類" },
  { id: "potato", name: "そうめん", category: "穀類" },
  { id: "potato", name: "中華めん", category: "穀類" },
  { id: "potato", name: "そば", category: "穀類" },
  { id: "potato", name: "薄力粉", category: "穀類" },
  { id: "potato", name: "マカロニ", category: "穀類" },
  { id: "potato", name: "スパゲティ", category: "穀類" },
  { id: "potato", name: "小麦粉", category: "穀類" },
  { id: "potato", name: "ホットケーキ用粉", category: "穀類" },
  { id: "potato", name: "ぎょうざの皮", category: "穀類" },
  { id: "potato", name: "パン粉", category: "穀類" },
  { id: "potato", name: "ビーフン", category: "穀類" },
  { id: "potato", name: "白玉粉", category: "穀類" },
  { id: "potato", name: "コーンフレーク", category: "穀類" },    
]
      
export const potatoes_starches_beans_mushrooms = [
  { id: "unspecified", name: "未指定", category: "未指定" },
  // potatoes
  { id:"sweet_potato", name: "さつまいも", category: "芋・でん粉・豆・キノコ類" },
  { id:"taro", name: "さといも", category: "芋・でん粉・豆・キノコ類" },
  { id:"potatoes", name: "じゃがいも", category: "芋・でん粉・豆・キノコ類" },
  { id:"nagaimo", name: "ながいも", category: "芋・でん粉・豆・キノコ類" },
  // starches
  { id:"konjac", name: "こんにゃく", category: "芋・でん粉・豆・キノコ類" },
  { id:"shirataki", name: "しらたき", category: "芋・でん粉・豆・キノコ類" },
  // beans
  { id:"peas", name: "えんどうまめ", category: "芋・でん粉・豆・キノコ類" },
  { id:"okara", name: "おから", category: "芋・でん粉・豆・キノコ類" },
  { id:"soy", name: "大豆", category: "芋・でん粉・豆・キノコ類" },
  { id:"soy_milk", name: "豆乳", category: "芋・でん粉・豆・キノコ類" },
  { id:"tofu", name: "豆腐", category: "芋・でん粉・豆・キノコ類" },
  { id:"natto", name: "納豆", category: "芋・でん粉・豆・キノコ類" },
  // mushrooms
  { id:"enokitake", name: "えのきたけ", category: "芋・でん粉・豆・キノコ類" },
  { id:"shiitake", name: "しいたけ", category: "芋・でん粉・豆・キノコ類" },
  { id:"nameko", name: "なめこ", category: "芋・でん粉・豆・キノコ類" },
  { id:"shimeji_mushroom", name: "しめじ", category: "芋・でん粉・豆・キノコ類" },
  { id:"maitake", name: "まいたけ", category: "芋・でん粉・豆・キノコ類" },
  { id:"mushroom", name: "マシュルーム", category: "芋・でん粉・豆・キノコ類" },


]